### ISSUE TITLE
Proposal: Reorganize how scenarios.py works

### ISSUE THREAD

**Issue by florianjehn** [allfed/allfed-integrated-model#67]
Right now we Scenario.py is only used as a kind of collection of hard coded data. This is then loaded into the variable inputs_to_optimizer and finally send over to the optimizer. 

I think this makes the code more difficult to read than it has to be. My proposal is the following:
- Make more use of Scenarios as a class
- Instead of sending data around, have it all in instances of Scenarios
- Let scenarios have a optimize and and parameters method, so you can directly call it from there. 

Pseudocode example:
\# create a new instance
baseline = Scenario()
\# Get all the data required for this kind of scenario
\# This could be more finegrained, doing it in one line is for the example
baseline.set_baseline_data()
\# computer the parameters
baseline.compute_parameters()
\# optimize it
baseline.optimize()

What do you think? @morganrivers 

This is related to #58, #17 and #12

**Comment by florianjehn** [comment]
One thing that I'd still have to understand is why the scenarios are optimized two times. For example, in https://github.com/allfed/allfed-integrated-model/blob/main/src/scenarios/run_model_baseline.py you optimize one time in line 81 and again in 115. Why?

**Comment by florianjehn** [comment]
Wild pitch: I think it might be less work in the long term to start the model from scratch, but adhere to test-driven development and good coding practices this time. Might be worth the effort if this project is meant to be the main thing ALLFED will be working with in the next few years.

**Comment by morganrivers** [comment]
the optimization the second time is in order to calculate diets -- 2100
kcals or so -- this is determined by subtracting all the waste and
converting an appropriate amount of feed going to animals and biofuels.
Turns out that what is left is human diets.

**Comment by morganrivers** [comment]
perhaps confusingly, "waste" includes metabolic waste (over-eating beyond
2100 kcals or other macronutrient requirements), so the result for a diet
pretty much always ends up close to 2100 kcals.

Obviously, this diet optimization doesn't work if the calories available
start out less than 2100 kcals. In that case, we might not expect meat and
biofuels to take up so much

**Comment by morganrivers** [comment]
Yeah, and the inputs_to_optimizer is really bad. Needs to just be a series
of food system class instantiations passed to and fro I think that contain
all the relevant constants as attributes.

A nutrition class or type is probably also called for. You know, so you can
have seaweed.nutrition.fat or something rather than
inputs_to_optimizer["inputs"]["SEAWEED_FAT"]

**Comment by florianjehn** [comment]
Thanks for the clarification. Seems like this is a good way to start once we begin to rewrite the model.

**Comment by florianjehn** [comment]
Morgan basically implemented this via refactoring

**Comment by morganrivers** [comment]
I think your proposal is sensible.

I think functionally, not much would be changed about the optimizer class,
because you would probably just import it and use it in the optimize call
to scenarios objec

I think analysis probably needs to be split into something like
get_data_from_optimizer which loops through and converts all the data from
the optimizer object in a cleaner and less hard coded way than it does now.
The validation steps in the analysis should probably be put into the
validator

The actual diet optimization where the appropriate amount of meat is
converted to food can be another function in the scenarios.

I am worried a little bit that scenarios becomes this unwieldy beast of a
file that is thousands of lines long though in this paradigm.

As mentioned, I don't mind the idea of starting from scratch, but we will
want to think hard about what features the second round needs
